### ISSUE TITLE
groovy-wrapper is incompatible with Gradle 8.3

### ISSUE THREAD

**Issue by donbex** [MovingBlocks/groovy-wrapper#8]
In Gradle 8.3, the signature of the `PathAssembler` constructor was changed from `PathAssembler(File gradleUserHome)` to `PathAssembler(File gradleUserHome, File projectDirectory)`, see https://github.com/gradle/gradle/commit/f99941b0190a36cddd0a72c37ce6b281520bbe02#diff-b3518ab2e45cdc6c02d663c2302abde57f3934d833b62532d65860f8faad17fb, making the current version of groovy-wrapper incompatible with Gradle 8.3.

In my basic testing, simply updating
https://github.com/MovingBlocks/groovy-wrapper/blob/7500e8c56c1dbfafae3d72bac22bc4dcda9b7f2c/src/main/java/org/gradle/wrapper/GroovyWrapperMain.java#L62
to use `new PathAssembler(gradleUserHome, rootDir))` appears to be enough to address the issue. However, a more careful fix will be necessary to preserve backwards compatibility.

**Comment by Cervator** [comment]
Thank you for the report! Sorry to have missed this for a while, been rather crazy lately.

We coincidentally upgraded to Gradle _8.2_ just a couple weeks ago via #9 and released as v2.2.0. Sounds like the same or similar issue, but I haven't tested specifically with 8.3. Want to see if that helps your use case?

Also from personal curiosity I'm always thrilled when somebody pops out of nowhere having noticed this tiny project, mind if I ask how you found it and what you're using it for? :-)

**Comment by donbex** [comment]
No worries, I understand. Yes, it looks like version 2.2.0 works with Gradle 8.3, at least in my limited testing.

My team's builds rely on Gradle and are relatively complex. We use Groovy for various ancillary scripting tasks, e.g. parsing JSON, and `groovyw` allows us to keep external build dependencies at a minimum, which is useful especially in CI environments. As for how we found it, I'm afraid I don't know: it was already in use before I joined my current employer.

**Comment by soloturn** [comment]
as we are on gradle-8.4 meanwhile this can be closed?

**Comment by donbex** [comment]
That's fine with me. As I said above, the recent changes seemed to fix the issue for me, although I didn't want to close it myself in case @Cervator had anything to add.

Anyway, I'll go ahead and close it now. Feel free to reopen if needed.
